


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.180:3306/cms_xz?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    cache.clusterNodes: 192.168.1.180:7001,192.168.1.180:7000,192.168.1.180:7002,192.168.1.180:7003,192.168.1.180:7004,192.168.1.180:7005
    cache.commandTimeout: 5000



#showSql
logging:
  level:
    com:
      example:
        com.luz.hormone.dao: debug


zk:
  root: /route
  connection: 192.168.1.15:2181
  iszk: true